---
title: "Propensity_Score_Matching_3"
author: "Jennifer"
date: "2025-11-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install Packages
```{r}
install.packages("memisc")
library("memisc")
library("tidyverse")
library("dplyr")
library("MatchIt")
library("optmatch")
library("cobalt")
```

## Read in the Dataset

```{r}
df <- read.csv('clean_dataset_export.csv')

head(df)
```
## 2020

```{r}
# Filter down to the 2020 cohort

cohort1 <- filter(df, Cohort_Factor == 1) %>%
  select(Treatment,
        Fall_2020_F_F_Registered_Factor,
        Gender_Factor,
        Academically_Disadvantaged_Factor,
        Enrollment_Status_Factor,
        TSIA_Math_College_Readiness_Factor,
        TSI_MATH_1_Factor,
        #TSI_MATH_2_Factor,
        Age_Factor,
        Fall_2020_Productive_Credit_Ratio_1,
        Fall_2020_HOURS_EARNED_x,
        Fall_2020_Academically_Eligible_Factor)

str(cohort1)
```

### 2020: Regression

```{r}
# Logistic Regression
# Estimates how the selected covariates influence the treatment.
log_reg_c1_model <- glm(Treatment ~
                        Gender_Factor +
                        Academically_Disadvantaged_Factor +
                        Enrollment_Status_Factor +
                        TSIA_Math_College_Readiness_Factor +
                        TSI_MATH_1_Factor +
                        #TSI_MATH_2_Factor +
                        Age_Factor +
                        Fall_2020_Productive_Credit_Ratio_1 +
                        Fall_2020_HOURS_EARNED_x +
                        Fall_2020_Academically_Eligible_Factor,
                        data = cohort1,
                        family="binomial")

summary(log_reg_c1_model)
```
### 2020: Propensity Score Matching

```{r}
# Replace the missing values with the mean.

#NA2mean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))
#replace(cohort1, TRUE, lapply(cohort1, NA2mean))

# OR drop missing values.
cohort1<- na.omit(cohort1)
```

```{r}
match_c1 <- matchit(Treatment ~
                    #Gender_Factor +
                    #Academically_Disadvantaged_Factor +
                    #Enrollment_Status_Factor +
                    TSIA_Math_College_Readiness_Factor +
                    #TSI_MATH_1_Factor +
                    #TSI_MATH_2_Factor +
                    #Age_Factor +
                    Fall_2020_Productive_Credit_Ratio_1 +
                    #Fall_2020_HOURS_EARNED_x +
                    Fall_2020_Academically_Eligible_Factor,
                    data = cohort1,
                    distance="glm",
                    method="full",
                    ratio=1)
match_c1

summary(match_c1)

# Means Treated: average value of the covariate over the treatment group.
# Means Control: average value of the covariate over the control group.
# Std. Mean Diff: difference in means between T and C, standardized by pre-match standard deviation. Closer to 0 = good balance.
# Variance Ratio: Closer to 1 = good balance.
# eCDF: empirical cumulative distribution functions.
```

```{r}
love.plot(bal.tab(match_c1), 
          stat = c("m","v"),
          grid=TRUE,
          threshold=c(m=.25,v=1.25))
```

### Analysis

```{r}
c1_matched <- match.data(match_c1)

model_c1 <- lm(Fall_2020_F_F_Registered_Factor ~ 
               Treatment +
               #Gender_Factor +
               #Academically_Disadvantaged_Factor +
               #Enrollment_Status_Factor +
               TSIA_Math_College_Readiness_Factor +
               #TSI_MATH_1_Factor +
               #TSI_MATH_2_Factor +
               #Age_Factor +
               Fall_2020_Productive_Credit_Ratio_1 +
               #Fall_2020_HOURS_EARNED_x +
               Fall_2020_Academically_Eligible_Factor,
             data = c1_matched,
             weights = weights)
summary(model_c1)
```

## 2021

```{r}
# Filter down to the 2021 cohort

cohort2 <- filter(df, Cohort_Factor == 2) %>%
  select(Treatment,
        Fall_2021_F_F_Registered_Factor,
        Gender_Factor,
        Academically_Disadvantaged_Factor,
        Enrollment_Status_Factor,
        TSIA_Math_College_Readiness_Factor,
        #TSI_MATH_1_Factor,
        #TSI_MATH_2_Factor,
        Age_Factor,
        Fall_2021_Productive_Credit_Ratio_1,
        Fall_2021_HOURS_EARNED_x,
        Fall_2021_Academically_Eligible_1)

str(cohort2)
```

### 2021: Regression

```{r}
# Logistic Regression
# Estimates how the selected covariates influence the treatment.
log_reg_2021_model <- glm(Treatment ~
                          Fall_2021_F_F_Registered_Factor +
                          Gender_Factor +
                          Academically_Disadvantaged_Factor +
                          Enrollment_Status_Factor +
                          TSIA_Math_College_Readiness_Factor +
                          #TSI_MATH_1_Factor +
                          #TSI_MATH_2_Factor +
                          Age_Factor +
                          Fall_2021_Productive_Credit_Ratio_1 +
                          Fall_2021_HOURS_EARNED_x +
                          Fall_2021_Academically_Eligible_1,
                          data = cohort2,
                          family="binomial")

summary(log_reg_2021_model)
```
### 2021: Propensity Score Matching

```{r}
# Omit Missing Values

cohort2<- na.omit(cohort2)
```

```{r}
match_c2 <- matchit(Treatment ~
                    #Gender_Factor +
                    #Academically_Disadvantaged_Factor +
                    #Enrollment_Status_Factor +
                    TSIA_Math_College_Readiness_Factor +
                    #TSI_MATH_1_Factor +
                    #TSI_MATH_2_Factor +
                    #Age_Factor +
                    Fall_2021_Productive_Credit_Ratio_1 +
                    #Fall_2021_HOURS_EARNED_x +
                    Fall_2021_Academically_Eligible_1,
                    data = cohort2,
                    distance="glm",
                    method="full",
                    ratio=1)
match_c2

summary(match_c2)
```

```{r}
love.plot(bal.tab(match_c2), 
          stat = c("m","v"),
          grid=TRUE,
          threshold=c(m=.25,v=1.25))
```

```{r}
c2_matched <- match.data(match_c2)

model_c2 <- lm(Fall_2021_F_F_Registered_Factor ~ 
               Treatment +
               #Gender_Factor +
               #Academically_Disadvantaged_Factor +
               #Enrollment_Status_Factor +
               TSIA_Math_College_Readiness_Factor +
               #TSI_MATH_1_Factor +
               #TSI_MATH_2_Factor +
               #Age_Factor +
               Fall_2021_Productive_Credit_Ratio_1 +
               #Fall_2021_HOURS_EARNED_x +
               Fall_2021_Academically_Eligible_1,
             data = c2_matched,
             weights = weights)
summary(model_c2)
```

