---
title: "Retention Analysis"
author: "Jennifer"
date: "2025-11-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install Packages
```{r}
library("ggplot2")
library("memisc")
library("tidyverse")
library("dplyr")
library("MatchIt")
library("optmatch")
library("cobalt")
```

## Read in the Dataset

```{r}
df <- read.csv('clean_dataset_export.csv')

head(df)
```
## 2020 / Cohort 1

```{r}
# Filter down to 2020 / Cohort 1

cohort1 <- filter(df, Cohort_Factor == 1) %>%
           select(Treatment,
                 F2020_F2021_Retention,
                 Gender_Factor,
                 Academically_Disadvantaged_Factor,
                 Enrollment_Status_Factor,
                 TSIA_Math_College_Readiness_Factor,
                 #TSI_MATH_1_Factor,
                 #TSI_MATH_2_Factor,
                 Age_Factor,
                 Fall_2020_Productive_Credit_Ratio_1,
                 Fall_2020_HOURS_EARNED_x,
                 Fall_2020_Academically_Eligible_Factor,
                 Fall_2020_GPA_4,
                 Fall_2020_GPA_5)
```

### Logistic Regression

```{r}
# Logistic Regression (NOT UPDATED)
# Estimates how the selected covariates influence the treatment.
log_reg_2020_model <- glm(Treatment ~
                          Gender_Factor +
                          Academically_Disadvantaged_Factor +
                          Enrollment_Status_Factor +
                          TSIA_Math_College_Readiness_Factor +
                          #TSI_MATH_1_Factor +
                          #TSI_MATH_2_Factor +
                          Age_Factor +
                          Fall_2020_Productive_Credit_Ratio_1 +
                          Fall_2020_HOURS_EARNED_x +
                          Fall_2020_Academically_Eligible_Factor +
                          Fall_2020_GPA_x +
                          Spring_2021_GPA_x,
                          data = cohort1,
                          family="binomial")

summary(log_reg_2020_model)
```


### 2020 / Cohort 1: Propensity Score Matching

```{r}
# Replace the missing values with the mean.

#NA2mean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))
#replace(cohort1, TRUE, lapply(cohort1, NA2mean))

# OR drop missing values.
cohort1<- na.omit(cohort1)
```

```{r}
match_c1 <- matchit(Treatment ~
                    #Gender_Factor +
                    Academically_Disadvantaged_Factor +
                    #Enrollment_Status_Factor +
                    TSIA_Math_College_Readiness_Factor +
                    #TSI_MATH_1_Factor +
                    #TSI_MATH_2_Factor +
                    #Age_Factor +
                    #Fall_2020_Productive_Credit_Ratio_1 +
                    #Fall_2020_HOURS_EARNED_x +
                    Fall_2020_Academically_Eligible_Factor +
                    Fall_2020_GPA_4,
                    #Fall_2020_GPA_5,
                    data = cohort1,
                    distance="glm",
                    method="full",
                    ratio=1)
match_c1

summary(match_c1)

# Means Treated: average value of the covariate over the treatment group.
# Means Control: average value of the covariate over the control group.
# Std. Mean Diff: difference in means between T and C, standardized by pre-match standard deviation. Closer to 0 = good balance.
# Variance Ratio: Closer to 1 = good balance.
# eCDF: empirical cumulative distribution functions.
```

```{r}
love.plot(bal.tab(match_c1), 
          stat = c("m","v"),
          grid=TRUE,
          threshold=c(m=.25,v=1.25))
```

### Analysis

```{r}
c1_matched <- match.data(match_c1)

model_c1 <- lm(F2020_F2021_Retention ~ 
               Treatment +
               #Gender_Factor +
               Academically_Disadvantaged_Factor +
               #Enrollment_Status_Factor +
               TSIA_Math_College_Readiness_Factor +
               #TSI_MATH_1_Factor +
               #TSI_MATH_2_Factor +
               #Age_Factor +
               #Fall_2020_Productive_Credit_Ratio_1 +
               #Fall_2020_HOURS_EARNED_x +
               Fall_2020_Academically_Eligible_Factor +
               Fall_2020_GPA_4,
               #Fall_2020_GPA_5,
             data = c1_matched,
             weights = weights)
summary(model_c1)
```

## 2021

```{r}
# Filter down to the 2021 cohort

cohort2 <- filter(df, Cohort_Factor == 2) %>%
           select(Treatment,
                 F2021_F2022_Retention,
                 Gender_Factor,
                 Academically_Disadvantaged_Factor,
                 Enrollment_Status_Factor,
                 TSIA_Math_College_Readiness_Factor,
                 #TSI_MATH_1_Factor,
                 #TSI_MATH_2_Factor,
                 Age_Factor,
                 Fall_2021_Productive_Credit_Ratio_1,
                 Fall_2021_HOURS_EARNED_x,
                 Fall_2021_Academically_Eligible_1,
                 Fall_2021_GPA_4,
                 Fall_2021_GPA_5)
```

### Cohort 2 / 2021: Propensity Score Matching

```{r}
# Omit Missing Values

cohort2<- na.omit(cohort2)
```

```{r}
match_c2 <- matchit(Treatment ~
                    #Gender_Factor +
                    Academically_Disadvantaged_Factor +
                    #Enrollment_Status_Factor +
                    TSIA_Math_College_Readiness_Factor +
                    #TSI_MATH_1_Factor +
                    #TSI_MATH_2_Factor +
                    #Age_Factor +
                    #Fall_2021_Productive_Credit_Ratio_1 +
                    #Fall_2021_HOURS_EARNED_x +
                    Fall_2021_Academically_Eligible_1 +
                    Fall_2021_GPA_4,
                    #Fall_2021_GPA_5,
                    data = cohort2,
                    distance="glm",
                    method="full",
                    ratio=1)
match_c2

summary(match_c2)
```

```{r}
love.plot(bal.tab(match_c2), 
          stat = c("m","v"),
          grid=TRUE,
          threshold=c(m=.25,v=1.25))
```

```{r}
c2_matched <- match.data(match_c2)

model_c2 <- lm(F2021_F2022_Retention ~ 
               Treatment +
               #Gender_Factor +
               Academically_Disadvantaged_Factor +
               #Enrollment_Status_Factor +
               TSIA_Math_College_Readiness_Factor +
               #TSI_MATH_1_Factor +
               #TSI_MATH_2_Factor +
               #Age_Factor +
               #Fall_2021_Productive_Credit_Ratio_1 +
               #Fall_2021_HOURS_EARNED_x +
               Fall_2021_Academically_Eligible_1 +
               Fall_2021_GPA_4,
               #Fall_2021_GPA_5,
             data = c2_matched,
             weights = weights)
summary(model_c2)
```
## Cohort 3 / 2022

```{r}
# Filter down to the 2022 cohort

cohort3 <- filter(df, Cohort_Factor == 3) %>%
  select(Treatment,
        F2022_F2023_Retention,
        Gender_Factor,
        Academically_Disadvantaged_Factor,
        Enrollment_Status_Factor,
        TSIA_Math_College_Readiness_Factor,
        #TSI_MATH_1_Factor,
        #TSI_MATH_2_Factor,
        Age_Factor,
        Fall_2022_Productive_Credit_Ratio_1,
        Fall_2022_HOURS_EARNED_x,
        Fall_2022_Academically_Eligible_Factor,
        Fall_2022_GPA_4,
        Fall_2022_GPA_5)
```

### 2022: Propensity Score Matching

```{r}
# Omit Missing Values

cohort3<- na.omit(cohort3)
```

```{r}
match_c3 <- matchit(Treatment ~
                    #Gender_Factor +
                    #Academically_Disadvantaged_Factor +
                    #Enrollment_Status_Factor +
                    #TSIA_Math_College_Readiness_Factor +
                    #TSI_MATH_1_Factor +
                    #TSI_MATH_2_Factor +
                    #Age_Factor +
                    #Fall_2022_Productive_Credit_Ratio_1 +
                    #Fall_2022_HOURS_EARNED_x +
                    Fall_2022_Academically_Eligible_Factor +
                    Fall_2022_GPA_4,
                    #Fall_2022_GPA_5,
                    data = cohort3,
                    distance="glm",
                    method="full",
                    ratio=1)
match_c3

summary(match_c3)
```

```{r}
love.plot(bal.tab(match_c2), 
          stat = c("m","v"),
          grid=TRUE,
          threshold=c(m=.25,v=1.25))
```

```{r}
c3_matched <- match.data(match_c3)

model_c3 <- lm(F2022_F2023_Retention ~ 
               Treatment +
               #Gender_Factor +
               #Academically_Disadvantaged_Factor +
               #Enrollment_Status_Factor +
               #TSIA_Math_College_Readiness_Factor +
               #TSI_MATH_1_Factor +
               #TSI_MATH_2_Factor +
               #Age_Factor +
               #Fall_2022_Productive_Credit_Ratio_1 +
               #Fall_2022_HOURS_EARNED_x +
               Fall_2022_Academically_Eligible_Factor +
               Fall_2022_GPA_4,
               #Fall_2022_GPA_5,
             data = c3_matched,
             weights = weights)
summary(model_c3)
```

# Plots

## Number of Students (Promise vs. Total)

```{r}
df$Cohort_Factor_Labeled <- factor(df$Cohort_Factor, levels = c("Fall 2020", "Fall 2021", "Fall 2022", "Fall 2023", "Fall 2024"))

df$Cohort_Factor_Labeled[df$Cohort_Factor == 1] <- "Fall 2020"
df$Cohort_Factor_Labeled[df$Cohort_Factor == 2] <- "Fall 2021"
df$Cohort_Factor_Labeled[df$Cohort_Factor == 3] <- "Fall 2022"
df$Cohort_Factor_Labeled[df$Cohort_Factor == 4] <- "Fall 2023"
df$Cohort_Factor_Labeled[df$Cohort_Factor == 5] <- "Fall 2024"
```


```{r}
ggplot(df, aes(fill = FTIC_Status_y, x = Cohort_Factor_Labeled, y = frequency(FTIC_Status_y), label = frequency(FTIC_Status_y))) +
  geom_bar(position = "stack", stat = "identity") +
  scale_fill_manual(values = c(rgb(0.24, 0.73, 0.88), rgb(0.93, 0.29, 0.4)),
                    labels = c("Non-Promise", "Promise"),
                    name = "Promise Status") +
  ggtitle("First Time Students at Alamo Colleges Students (Fall 2020 - Fall 2024)") +
  labs(x = "Cohort", y = "Number of Students") +
  theme(panel.grid.minor = element_blank()) 
```

```{r}
# Frequency Counts for Manual Input

print(paste0("Fall 2020 Non-Promise: ", nrow(filter(df, Cohort_Factor == 1, Treatment == 0))))
print(paste0("Fall 2020 Promise: ", nrow(filter(df, Cohort_Factor == 1, Treatment == 1))))
print(paste0("Fall 2021 Non-Promise: ", nrow(filter(df, Cohort_Factor == 2, Treatment == 0))))
print(paste0("Fall 2021 Promise: ", nrow(filter(df, Cohort_Factor == 2, Treatment == 1))))
print(paste0("Fall 2022 Non-Promise: ", nrow(filter(df, Cohort_Factor == 3, Treatment == 0))))
print(paste0("Fall 2022 Promise: ", nrow(filter(df, Cohort_Factor == 3, Treatment == 1))))
print(paste0("Fall 2023 Non-Promise: ", nrow(filter(df, Cohort_Factor == 4, Treatment == 0))))
print(paste0("Fall 2023 Promise: ", nrow(filter(df, Cohort_Factor == 4, Treatment == 1))))
print(paste0("Fall 2024 Non-Promise: ", nrow(filter(df, Cohort_Factor == 5, Treatment == 0))))
print(paste0("Fall 2024 Promise: ", nrow(filter(df, Cohort_Factor == 5, Treatment == 1))))
```

